// tests/discovery/entity-shapes-enums.test.cjs
//
// Drift guard for the GENERATED closed-enum blocks in the avni-bundle-spec
// Skill's entity-shapes.md. Those blocks (dataType, privilegeType) are
// generated by scripts/build-bundle-spec-skill.mjs from the brain validator's
// VALID_* sets. This test asserts the staged blocks EXACTLY equal the brain
// validator's sets — same values, same order — so the lists can never silently
// drift from the server contract (mirrors bundle-spec-checksum.test.cjs).
//
// It also PINS the formType enum: entity-shapes.md intentionally lists only the
// FK-relevant subset of formTypes (the ones in the FK matrix), so we don't
// generate it — but we assert every listed value is a real member of the
// validator's VALID_FORM_TYPES, so a typo or a server-contract change is caught.
//
// Needs AVNI_SKILLS_PATH (or a sibling avni-skills). If the brain is absent the
// drift assertions SKIP cleanly — it's a drift guard, not a brain-availability
// gate. No API spend — pure file + string checks.

"use strict";

const { test } = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const SDK_DIR = path.resolve(__dirname, "..", "..");
const ENTITY_SHAPES = path.join(
  SDK_DIR, "skills", "avni-bundle-spec", "reference", "entity-shapes.md",
);

function resolveBrainPath() {
  if (process.env.AVNI_SKILLS_PATH) return process.env.AVNI_SKILLS_PATH;
  return path.resolve(SDK_DIR, "..", "avni-skills");
}
function validatorPath() {
  return path.join(
    resolveBrainPath(), "srs-bundle-generator", "validators", "bundle_validator.js",
  );
}

// Extract the string members of a `const <NAME> = new Set([ ... ]);` literal,
// in source order. Mirrors scripts/build-bundle-spec-skill.mjs:extractValidatorSet.
function extractValidatorSet(name, src) {
  const re = new RegExp(`const\\s+${name}\\s*=\\s*new Set\\(\\[([\\s\\S]*?)\\]\\)`);
  const m = src.match(re);
  assert.ok(m, `could not find "const ${name} = new Set([...])" in the brain validator`);
  return [...m[1].matchAll(/'([^']+)'|"([^"]+)"/g)].map((x) => x[1] ?? x[2]);
}

// Pull the comma/whitespace-separated tokens out of a GENERATED:<key> fenced
// block in entity-shapes.md.
function generatedEnumTokens(docText, key) {
  const startTag = `<!-- GENERATED:${key}`;
  const endTag = `<!-- /GENERATED:${key} -->`;
  const sIdx = docText.indexOf(startTag);
  const eIdx = docText.indexOf(endTag);
  assert.ok(sIdx !== -1 && eIdx !== -1,
    `entity-shapes.md is missing the GENERATED:${key} sentinel block — run npm run build:bundle-spec-skill`);
  const region = docText.slice(sIdx, eIdx);
  const fence = region.match(/```\n([\s\S]*?)\n```/);
  assert.ok(fence, `GENERATED:${key} block has no fenced enum list`);
  return fence[1]
    .split(/[\s,]+/)
    .map((t) => t.trim())
    .filter(Boolean);
}

// formType list lives in its own un-generated F9 fenced block.
function formTypeTokens(docText) {
  const m = docText.match(/### `formType` — closed enum \(F9\)\s*\n+```\n([\s\S]*?)\n```/);
  assert.ok(m, "could not find the formType (F9) fenced block in entity-shapes.md");
  return m[1].split(/[\s,]+/).map((t) => t.trim()).filter(Boolean);
}

const brainPresent = fs.existsSync(validatorPath());

test("entity-shapes.md: GENERATED dataType block exactly equals validator VALID_DATA_TYPES", (t) => {
  if (!brainPresent) {
    t.skip(`brain validator not found at ${validatorPath()} (set AVNI_SKILLS_PATH) — drift guard skipped`);
    return;
  }
  const src = fs.readFileSync(validatorPath(), "utf8");
  const canonical = extractValidatorSet("VALID_DATA_TYPES", src);
  const doc = fs.readFileSync(ENTITY_SHAPES, "utf8");
  const staged = generatedEnumTokens(doc, "dataType");
  assert.deepEqual(
    staged, canonical,
    "dataType enum in entity-shapes.md has drifted from the brain validator's " +
    "VALID_DATA_TYPES. Re-run `npm run build:bundle-spec-skill` to regenerate.",
  );
});

test("entity-shapes.md: GENERATED privilegeType block exactly equals validator VALID_PRIVILEGE_TYPES", (t) => {
  if (!brainPresent) {
    t.skip(`brain validator not found at ${validatorPath()} (set AVNI_SKILLS_PATH) — drift guard skipped`);
    return;
  }
  const src = fs.readFileSync(validatorPath(), "utf8");
  const canonical = extractValidatorSet("VALID_PRIVILEGE_TYPES", src);
  const doc = fs.readFileSync(ENTITY_SHAPES, "utf8");
  const staged = generatedEnumTokens(doc, "privilegeType");

  // Exact, order-sensitive equality — the generator preserves source order.
  assert.deepEqual(
    staged, canonical,
    "privilegeType enum in entity-shapes.md has drifted from the brain validator's " +
    "VALID_PRIVILEGE_TYPES. Re-run `npm run build:bundle-spec-skill` to regenerate.",
  );

  // Belt-and-braces: the four invalid values the hand-written list used to carry
  // must NOT reappear (they trip G2).
  for (const bad of ["UnVoidSubject", "VoidEnrolment", "UnVoidEnrolment", "UnVoidVisit"]) {
    assert.ok(!staged.includes(bad),
      `"${bad}" is NOT a valid privilegeType (not in the server enum) — it must not appear in entity-shapes.md`);
  }
});

test("entity-shapes.md: every listed formType is a real member of validator VALID_FORM_TYPES (pinned, not generated)", (t) => {
  if (!brainPresent) {
    t.skip(`brain validator not found at ${validatorPath()} (set AVNI_SKILLS_PATH) — drift guard skipped`);
    return;
  }
  const src = fs.readFileSync(validatorPath(), "utf8");
  const validFormTypes = new Set(extractValidatorSet("VALID_FORM_TYPES", src));
  const doc = fs.readFileSync(ENTITY_SHAPES, "utf8");
  const listed = formTypeTokens(doc);
  assert.ok(listed.length > 0, "no formType values found in entity-shapes.md");
  for (const ft of listed) {
    assert.ok(validFormTypes.has(ft),
      `formType "${ft}" listed in entity-shapes.md is NOT in the brain validator's VALID_FORM_TYPES`);
  }
});

test("entity-shapes.md: GENERATED blocks carry a provenance comment naming the validator + a value-sha256", () => {
  const doc = fs.readFileSync(ENTITY_SHAPES, "utf8");
  for (const key of ["dataType", "privilegeType"]) {
    const m = doc.match(new RegExp(`<!-- provenance:${key}([\\s\\S]*?)/provenance:${key} -->`));
    assert.ok(m, `entity-shapes.md is missing the provenance:${key} block`);
    assert.match(m[1], /source-path:\s+srs-bundle-generator\/validators\/bundle_validator\.js/,
      `provenance:${key} must name the validator source path`);
    assert.match(m[1], /value-sha256:\s+[0-9a-f]{64}/,
      `provenance:${key} must record a value-sha256`);
  }
});
